pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        mavenCentral()
    }
}


plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}


include 'cascara-common-io'
include 'common-io-test'
// include 'common-io-test-providers'
